#!/bin/bash

umask 0002
as-developer true   # ensure dev exists

# Ensure data subdirs exist
for sub in cache cache/prod logs config media/uploads media/files translations; do
    mkdir -p "$MAUTIC_DATA/$sub"
    chown developer:nginx "$MAUTIC_DATA/$sub"
    chmod g+ws "$MAUTIC_DATA/$sub"
done

# Route image uploads and translations to data volume
for sub in media/uploads translations; do
	[[ -L "$MAUTIC_DATA/$sub" ]] || rm -rf "$CODE_BASE/$sub"
	ln -s "$MAUTIC_DATA/$sub" "$CODE_BASE/$sub"
done

# Force regenerate cached configuration to ensure it's consistent with the
# current environment, as set by parameters_local.php
rm "$MAUTIC_DATA/cache/prod/appProdProjectContainer".*
as-developer php app/console cache:warmup --no-optional-warmers