#!/bin/bash

umask 0002
as-developer true   # ensure dev exists

# Ensure data subdirs exist
for sub in cache cache/prod logs config media/uploads media/files tmp translations; do
    mkdir -p "$MAUTIC_DATA/$sub"
    chown developer:nginx "$MAUTIC_DATA/$sub"
    chmod g+s "$MAUTIC_DATA/$sub"
    chmod -R g+w "$MAUTIC_DATA/$sub"
done

# Create default config
[[ -f "$MAUTIC_DATA"/config/local.php ]] || as-nginx \
	cp "$CODE_BASE"/app/config/parameters_local.php "$MAUTIC_DATA"/config/local.php

# Route image uploads and translations to data volume
for sub in media/uploads translations app/cache app/logs; do
	[[ -L "$MAUTIC_DATA/$sub" ]] || rm -rf "$CODE_BASE/$sub"
	ln -sfn "$MAUTIC_DATA/${sub#app/}" "$CODE_BASE/$sub"
done

# Force regenerate cached configuration to ensure it's consistent with the
# current environment, as set by parameters_local.php
rm "$MAUTIC_DATA/cache/prod/appProdProjectContainer".* 2>/dev/null

if [[ "$DB_USER" && "$DB_NAME" ]]; then
	# Create a DB if needed, and regenerate the config cache as a side-effect
	as-developer php app/console doctrine:database:create --if-not-exists || true
fi

# Force full warmup
as-developer php app/console cache:warmup
